name: CI
on: 
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.3'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -B -m pytest

      - name: Black formatting
        uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check].
          reporter: github-pr-check
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with a warning.
          level: warning
          verbose: true
      