name: CI
on: 
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.3'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -B -m pytest

      - name: Check Black formatting
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
      