name: CI
on: 
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  setup-python:
    name: Set up Python environment
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.setup-python.outputs.python-version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.3'

      - name: Create venv and install packages
        run: |
          python3 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          pip install -r requirements.txt
     
      - name: Run pytest tests
        run: python -B -m pytest
  
  black-format:
    name: Black formatting
    needs: setup-python
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Black formatting
        uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check.
          level: warning
          verbose: true
      
